// Code generated by protoc-gen-go. DO NOT EDIT.
// source: booking/booking.proto

package booking

import (
	context "context"
	fmt "fmt"
	room "github.com/devopsprodigy/meeting-proto-uuid/room"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Booking struct {
	Id                   []byte               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	RoomId               []byte               `protobuf:"bytes,5,opt,name=roomId,proto3" json:"roomId,omitempty"`
	UserId               []byte               `protobuf:"bytes,6,opt,name=userId,proto3" json:"userId,omitempty"`
	ParticipantsId       [][]byte             `protobuf:"bytes,7,rep,name=participantsId,proto3" json:"participantsId,omitempty"`
	Room                 *room.RoomModel      `protobuf:"bytes,8,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Booking) Reset()         { *m = Booking{} }
func (m *Booking) String() string { return proto.CompactTextString(m) }
func (*Booking) ProtoMessage()    {}
func (*Booking) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ffdf80b5823d65, []int{0}
}

func (m *Booking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Booking.Unmarshal(m, b)
}
func (m *Booking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Booking.Marshal(b, m, deterministic)
}
func (m *Booking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Booking.Merge(m, src)
}
func (m *Booking) XXX_Size() int {
	return xxx_messageInfo_Booking.Size(m)
}
func (m *Booking) XXX_DiscardUnknown() {
	xxx_messageInfo_Booking.DiscardUnknown(m)
}

var xxx_messageInfo_Booking proto.InternalMessageInfo

func (m *Booking) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Booking) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Booking) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Booking) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Booking) GetRoomId() []byte {
	if m != nil {
		return m.RoomId
	}
	return nil
}

func (m *Booking) GetUserId() []byte {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *Booking) GetParticipantsId() [][]byte {
	if m != nil {
		return m.ParticipantsId
	}
	return nil
}

func (m *Booking) GetRoom() *room.RoomModel {
	if m != nil {
		return m.Room
	}
	return nil
}

type CreateReq struct {
	Booking              *Booking `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ffdf80b5823d65, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetBooking() *Booking {
	if m != nil {
		return m.Booking
	}
	return nil
}

type CreateRes struct {
	Booking              *Booking `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRes) Reset()         { *m = CreateRes{} }
func (m *CreateRes) String() string { return proto.CompactTextString(m) }
func (*CreateRes) ProtoMessage()    {}
func (*CreateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ffdf80b5823d65, []int{2}
}

func (m *CreateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRes.Unmarshal(m, b)
}
func (m *CreateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRes.Marshal(b, m, deterministic)
}
func (m *CreateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRes.Merge(m, src)
}
func (m *CreateRes) XXX_Size() int {
	return xxx_messageInfo_CreateRes.Size(m)
}
func (m *CreateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRes proto.InternalMessageInfo

func (m *CreateRes) GetBooking() *Booking {
	if m != nil {
		return m.Booking
	}
	return nil
}

type FindReq struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindReq) Reset()         { *m = FindReq{} }
func (m *FindReq) String() string { return proto.CompactTextString(m) }
func (*FindReq) ProtoMessage()    {}
func (*FindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ffdf80b5823d65, []int{3}
}

func (m *FindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindReq.Unmarshal(m, b)
}
func (m *FindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindReq.Marshal(b, m, deterministic)
}
func (m *FindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindReq.Merge(m, src)
}
func (m *FindReq) XXX_Size() int {
	return xxx_messageInfo_FindReq.Size(m)
}
func (m *FindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindReq proto.InternalMessageInfo

func (m *FindReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *FindReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type FindRes struct {
	Booking              []*Booking `protobuf:"bytes,1,rep,name=booking,proto3" json:"booking,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindRes) Reset()         { *m = FindRes{} }
func (m *FindRes) String() string { return proto.CompactTextString(m) }
func (*FindRes) ProtoMessage()    {}
func (*FindRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_00ffdf80b5823d65, []int{4}
}

func (m *FindRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRes.Unmarshal(m, b)
}
func (m *FindRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRes.Marshal(b, m, deterministic)
}
func (m *FindRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRes.Merge(m, src)
}
func (m *FindRes) XXX_Size() int {
	return xxx_messageInfo_FindRes.Size(m)
}
func (m *FindRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindRes proto.InternalMessageInfo

func (m *FindRes) GetBooking() []*Booking {
	if m != nil {
		return m.Booking
	}
	return nil
}

func init() {
	proto.RegisterType((*Booking)(nil), "booking.Booking")
	proto.RegisterType((*CreateReq)(nil), "booking.CreateReq")
	proto.RegisterType((*CreateRes)(nil), "booking.CreateRes")
	proto.RegisterType((*FindReq)(nil), "booking.FindReq")
	proto.RegisterType((*FindRes)(nil), "booking.FindRes")
}

func init() { proto.RegisterFile("booking/booking.proto", fileDescriptor_00ffdf80b5823d65) }

var fileDescriptor_00ffdf80b5823d65 = []byte{
	// 388 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0xa6, 0x6d, 0x5e, 0xf2, 0xba, 0x7d, 0xb4, 0x8f, 0x01, 0x25, 0x04, 0xc1, 0x52, 0x41, 0x44,
	0x68, 0x22, 0xad, 0x45, 0xaf, 0x56, 0x10, 0x3c, 0x78, 0x89, 0x3d, 0x79, 0x4b, 0xba, 0x63, 0x5c,
	0x6c, 0xb2, 0x31, 0xd9, 0x14, 0xfc, 0x2b, 0xfe, 0x5a, 0x37, 0xbb, 0xd9, 0xb6, 0x54, 0x50, 0xbc,
	0x24, 0x3b, 0xdf, 0xcc, 0xb7, 0xdf, 0xce, 0x37, 0x43, 0x0e, 0x62, 0xce, 0x5f, 0x59, 0x96, 0x04,
	0xcd, 0xdf, 0xcf, 0x0b, 0x2e, 0x38, 0x38, 0x4d, 0xe8, 0x0d, 0x0a, 0xce, 0xd3, 0xa0, 0xfe, 0xe8,
	0x8c, 0x77, 0x9c, 0x70, 0x9e, 0xac, 0x30, 0x50, 0x51, 0x5c, 0x3d, 0x07, 0x82, 0xa5, 0x58, 0x8a,
	0x28, 0xcd, 0x75, 0xc1, 0xe8, 0xa3, 0x4d, 0x9c, 0xb9, 0x66, 0x43, 0x9f, 0xb4, 0x19, 0x75, 0x5b,
	0xc3, 0xd6, 0xd9, 0xbf, 0x50, 0x9e, 0x00, 0x88, 0x95, 0x45, 0x29, 0xba, 0x6d, 0x89, 0x74, 0x43,
	0x75, 0x86, 0x6b, 0xd2, 0x95, 0xf4, 0x42, 0x2c, 0xe4, 0x3d, 0x6e, 0x47, 0x26, 0x7a, 0x13, 0xcf,
	0xd7, 0x22, 0xbe, 0x11, 0xf1, 0x17, 0x46, 0x24, 0xdc, 0x16, 0xc3, 0x25, 0x71, 0x30, 0xa3, 0x8a,
	0x67, 0xfd, 0xc8, 0x33, 0xa5, 0x70, 0x48, 0xec, 0xba, 0x9d, 0x7b, 0xea, 0xfe, 0x51, 0xef, 0x6a,
	0xa2, 0x1a, 0xaf, 0x4a, 0x2c, 0x24, 0x6e, 0x6b, 0x5c, 0x47, 0x70, 0x4a, 0xfa, 0xb9, 0x54, 0x64,
	0x4b, 0x96, 0x47, 0x99, 0x28, 0x65, 0xde, 0x19, 0x76, 0x64, 0x7e, 0x0f, 0x85, 0x13, 0x62, 0xd5,
	0x37, 0xb9, 0x7f, 0xd5, 0x53, 0x06, 0xbe, 0xf2, 0x2c, 0x94, 0x9f, 0x07, 0x4e, 0x71, 0x15, 0xaa,
	0xe4, 0xe8, 0x8a, 0x74, 0x6f, 0x0b, 0x8c, 0x04, 0x86, 0xf8, 0x06, 0xe7, 0xc4, 0xd8, 0xac, 0x2c,
	0xea, 0x4d, 0xfe, 0xfb, 0x66, 0x0a, 0x8d, 0x81, 0xa1, 0x29, 0xd8, 0x25, 0x96, 0xbf, 0x22, 0xde,
	0x10, 0xe7, 0x8e, 0x65, 0xb4, 0xd6, 0x3b, 0xda, 0x75, 0xba, 0xa5, 0x46, 0xb0, 0xe3, 0xa6, 0xbb,
	0x75, 0x53, 0x8f, 0xc7, 0x84, 0xa3, 0x99, 0xb9, 0x62, 0x4f, 0xb9, 0xf3, 0xad, 0xf2, 0x24, 0x23,
	0xfd, 0x06, 0x7b, 0xc4, 0x62, 0xcd, 0x96, 0x08, 0x17, 0xc4, 0xd6, 0x4d, 0x00, 0x6c, 0x68, 0x1b,
	0x3b, 0xbc, 0xaf, 0x58, 0xad, 0x67, 0xd5, 0xd2, 0xb0, 0x95, 0x69, 0x9a, 0xf1, 0xf6, 0x91, 0x72,
	0x3e, 0x7b, 0x9a, 0x26, 0x4c, 0xbc, 0x54, 0xb1, 0xbf, 0x94, 0x2b, 0x4b, 0x71, 0xcd, 0xf3, 0x52,
	0x2e, 0x02, 0x65, 0xc9, 0x7b, 0x90, 0x22, 0x0a, 0x59, 0x3b, 0x56, 0x8b, 0x31, 0xae, 0x2a, 0x46,
	0xcd, 0xc2, 0xc7, 0xb6, 0xc2, 0xa6, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7c, 0x40, 0xf4, 0x2b,
	0x0a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error)
	Find(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error)
}

type bookingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookingServiceClient(cc *grpc.ClientConn) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateRes, error) {
	out := new(CreateRes)
	err := c.cc.Invoke(ctx, "/booking.BookingService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) Find(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/booking.BookingService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
type BookingServiceServer interface {
	Create(context.Context, *CreateReq) (*CreateRes, error)
	Find(context.Context, *FindReq) (*FindRes, error)
}

// UnimplementedBookingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (*UnimplementedBookingServiceServer) Create(ctx context.Context, req *CreateReq) (*CreateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBookingServiceServer) Find(ctx context.Context, req *FindReq) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterBookingServiceServer(s *grpc.Server, srv BookingServiceServer) {
	s.RegisterService(&_BookingService_serviceDesc, srv)
}

func _BookingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.BookingService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.BookingService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).Find(ctx, req.(*FindReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "booking.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BookingService_Create_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _BookingService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "booking/booking.proto",
}
