// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   []byte   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Telegram             string   `protobuf:"bytes,4,opt,name=telegram,proto3" json:"telegram,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetTelegram() string {
	if m != nil {
		return m.Telegram
	}
	return ""
}

type FindReq struct {
	Id                   [][]byte `protobuf:"bytes,1,rep,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindReq) Reset()         { *m = FindReq{} }
func (m *FindReq) String() string { return proto.CompactTextString(m) }
func (*FindReq) ProtoMessage()    {}
func (*FindReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{1}
}

func (m *FindReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindReq.Unmarshal(m, b)
}
func (m *FindReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindReq.Marshal(b, m, deterministic)
}
func (m *FindReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindReq.Merge(m, src)
}
func (m *FindReq) XXX_Size() int {
	return xxx_messageInfo_FindReq.Size(m)
}
func (m *FindReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindReq proto.InternalMessageInfo

func (m *FindReq) GetId() [][]byte {
	if m != nil {
		return m.Id
	}
	return nil
}

type FindRes struct {
	Booking              []*User  `protobuf:"bytes,1,rep,name=booking,proto3" json:"booking,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindRes) Reset()         { *m = FindRes{} }
func (m *FindRes) String() string { return proto.CompactTextString(m) }
func (*FindRes) ProtoMessage()    {}
func (*FindRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed89022014131a74, []int{2}
}

func (m *FindRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindRes.Unmarshal(m, b)
}
func (m *FindRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindRes.Marshal(b, m, deterministic)
}
func (m *FindRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindRes.Merge(m, src)
}
func (m *FindRes) XXX_Size() int {
	return xxx_messageInfo_FindRes.Size(m)
}
func (m *FindRes) XXX_DiscardUnknown() {
	xxx_messageInfo_FindRes.DiscardUnknown(m)
}

var xxx_messageInfo_FindRes proto.InternalMessageInfo

func (m *FindRes) GetBooking() []*User {
	if m != nil {
		return m.Booking
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*FindReq)(nil), "user.FindReq")
	proto.RegisterType((*FindRes)(nil), "user.FindRes")
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor_ed89022014131a74) }

var fileDescriptor_ed89022014131a74 = []byte{
	// 237 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x50, 0x3d, 0x4f, 0xc3, 0x30,
	0x10, 0x55, 0xdb, 0x40, 0xcb, 0x95, 0x0f, 0xe9, 0xc4, 0x10, 0x3a, 0xa1, 0x88, 0xa1, 0x4b, 0x13,
	0x14, 0x06, 0xf6, 0x0e, 0x48, 0xac, 0x41, 0x2c, 0x88, 0x25, 0xa9, 0x4f, 0xe1, 0x44, 0x1d, 0x97,
	0xd8, 0xae, 0xd4, 0x7f, 0x8f, 0x7d, 0xa1, 0x95, 0x58, 0xec, 0xf7, 0x61, 0xdf, 0x3b, 0x3d, 0xb8,
	0xf1, 0x96, 0xfa, 0x22, 0x1e, 0xf9, 0xae, 0x37, 0xce, 0x60, 0x12, 0x71, 0xf6, 0x09, 0xc9, 0x7b,
	0xb8, 0xf1, 0x1a, 0xc6, 0xac, 0xd2, 0xd1, 0xfd, 0x68, 0x79, 0x59, 0x05, 0x84, 0x08, 0x49, 0x57,
	0x6b, 0x4a, 0xc7, 0x41, 0xb9, 0xa8, 0x04, 0xe3, 0x2d, 0x9c, 0x91, 0xae, 0x79, 0x9b, 0x4e, 0x44,
	0x1c, 0x08, 0x2e, 0x60, 0xe6, 0x68, 0x4b, 0x6d, 0x5f, 0xeb, 0x34, 0x11, 0xe3, 0xc4, 0xb3, 0x3b,
	0x98, 0xbe, 0x70, 0xa7, 0x2a, 0xfa, 0x39, 0x05, 0x4c, 0x86, 0x80, 0xac, 0x38, 0x5a, 0x16, 0x1f,
	0x60, 0xda, 0x18, 0xf3, 0xcd, 0x5d, 0x2b, 0xfe, 0xbc, 0x84, 0x5c, 0xf6, 0x8c, 0x8b, 0x55, 0x47,
	0xab, 0x7c, 0x86, 0x79, 0x14, 0xde, 0xa8, 0xdf, 0xf3, 0x86, 0x70, 0x09, 0xb3, 0xf8, 0x7f, 0x7d,
	0x78, 0x55, 0x78, 0x35, 0xbc, 0xff, 0x8b, 0x5a, 0xfc, 0xa3, 0x76, 0x5d, 0x7e, 0x3c, 0xb6, 0xec,
	0xbe, 0x7c, 0x93, 0x6f, 0x8c, 0x2e, 0x14, 0xed, 0xcd, 0xce, 0x86, 0x0a, 0x14, 0xb7, 0x87, 0x42,
	0x13, 0xb9, 0x30, 0x7c, 0x25, 0x95, 0xac, 0xbc, 0x67, 0x25, 0x15, 0x35, 0xe7, 0x22, 0x3c, 0xfd,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x5d, 0x11, 0x5d, 0x1d, 0x36, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	FindById(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) FindById(ctx context.Context, in *FindReq, opts ...grpc.CallOption) (*FindRes, error) {
	out := new(FindRes)
	err := c.cc.Invoke(ctx, "/user.UserService/FindById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	FindById(context.Context, *FindReq) (*FindRes, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) FindById(ctx context.Context, req *FindReq) (*FindRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindById not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_FindById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FindById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/FindById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FindById(ctx, req.(*FindReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindById",
			Handler:    _UserService_FindById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
